// src/ui/components/AppearanceMenu.svelte
<script lang="ts">
  import type { ThemeDensity, ThemeFamily } from "../../runtime/types";
  import { theme } from "../theme.svelte";

  const families: Array<{ family: ThemeFamily; label: string; description: string }> = [
    { family: "atlas", label: "Atlas", description: "Editorial technical reference" },
    { family: "blueprint", label: "Blueprint", description: "Structured and schematic" },
    { family: "terminal", label: "Terminal", description: "Compact operational console" },
    { family: "editorial", label: "Editorial", description: "Spacious publication reading" },
  ];

  let isOpen = $state(false);
  let menuElement: HTMLDivElement | null = null;

  $effect(() => {
    if (!isOpen) return;

    const closeOnOutsidePointer = (event: MouseEvent) => {
      if (!menuElement?.contains(event.target as Node)) isOpen = false;
    };
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") isOpen = false;
    };

    document.addEventListener("mousedown", closeOnOutsidePointer);
    document.addEventListener("keydown", closeOnEscape);
    return () => {
      document.removeEventListener("mousedown", closeOnOutsidePointer);
      document.removeEventListener("keydown", closeOnEscape);
    };
  });
</script>

<div class="dmd-appearance" bind:this={menuElement}>
  <button
    type="button"
    class="dmd-appearance-trigger"
    aria-expanded={isOpen}
    aria-haspopup="dialog"
    onclick={() => (isOpen = !isOpen)}
  >
    <span class="dmd-theme-mark dmd-theme-mark-{theme.family}" aria-hidden="true"></span>
    <span class="dmd-appearance-trigger-label">Appearance</span>
  </button>

  {#if isOpen}
    <div class="dmd-appearance-panel" role="dialog" aria-label="Documentation appearance">
      <div class="dmd-appearance-heading">
        <span>Appearance</span>
        <button type="button" class="dmd-appearance-close" aria-label="Close appearance menu" onclick={() => (isOpen = false)}>
          ×
        </button>
      </div>

      <div class="dmd-appearance-section">
        <div class="dmd-appearance-label">Theme family</div>
        <div class="dmd-theme-family-grid">
          {#each families as item (item.family)}
            <button
              type="button"
              class="dmd-theme-family-card {theme.family === item.family ? "active" : ""}"
              aria-pressed={theme.family === item.family}
              onclick={() => theme.setFamily(item.family)}
            >
              <span class="dmd-theme-preview dmd-theme-preview-{item.family}" aria-hidden="true">
                <span></span>
                <span></span>
                <span></span>
              </span>
              <span class="dmd-theme-family-name">{item.label}</span>
              <span class="dmd-theme-family-description">{item.description}</span>
            </button>
          {/each}
        </div>
      </div>

      <fieldset class="dmd-appearance-section">
        <legend class="dmd-appearance-label">Mode</legend>
        <div class="dmd-segmented-control">
          {#each ["auto", "light", "dark"] as item (item)}
            <button type="button" class={theme.mode === item ? "active" : ""} onclick={() => theme.setMode(item as any)}>
              {item}
            </button>
          {/each}
        </div>
        <button type="button" class="dmd-appearance-quick-mode" onclick={() => theme.toggleMode()}>
          Use {theme.resolvedMode === "dark" ? "light" : "dark"} now
        </button>
      </fieldset>

      <fieldset class="dmd-appearance-section">
        <legend class="dmd-appearance-label">Reading density</legend>
        <div class="dmd-segmented-control">
          {#each ["comfortable", "compact"] as item (item)}
            <button
              type="button"
              class={theme.density === (item as ThemeDensity) ? "active" : ""}
              onclick={() => theme.setDensity(item as ThemeDensity)}
            >
              {item}
            </button>
          {/each}
        </div>
      </fieldset>
    </div>
  {/if}
</div>

// src/runtime/components/AppearanceMenu.tsx
import type React from "react";
import { useEffect, useRef, useState } from "react";
import { useTheme } from "../provider/ThemeProvider";
import type { ThemeDensity, ThemeFamily } from "../types";

const families: Array<{ family: ThemeFamily; label: string; description: string }> = [
  { family: "atlas", label: "Atlas", description: "Editorial technical reference" },
  { family: "blueprint", label: "Blueprint", description: "Structured and schematic" },
  { family: "terminal", label: "Terminal", description: "Compact operational console" },
  { family: "editorial", label: "Editorial", description: "Spacious publication reading" },
];

export const AppearanceMenu: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const { family, density, mode, resolvedMode, setFamily, setDensity, setMode, toggleMode } = useTheme();

  useEffect(() => {
    if (!isOpen) return;

    const closeOnOutsidePointer = (event: MouseEvent) => {
      if (!menuRef.current?.contains(event.target as Node)) setIsOpen(false);
    };
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") setIsOpen(false);
    };

    document.addEventListener("mousedown", closeOnOutsidePointer);
    document.addEventListener("keydown", closeOnEscape);
    return () => {
      document.removeEventListener("mousedown", closeOnOutsidePointer);
      document.removeEventListener("keydown", closeOnEscape);
    };
  }, [isOpen]);

  return (
    <div className="dmd-appearance" ref={menuRef}>
      <button
        type="button"
        className="dmd-appearance-trigger"
        aria-expanded={isOpen}
        aria-haspopup="dialog"
        onClick={() => setIsOpen((open) => !open)}
      >
        <span className={`dmd-theme-mark dmd-theme-mark-${family}`} aria-hidden="true" />
        <span className="dmd-appearance-trigger-label">Appearance</span>
      </button>

      {isOpen && (
        <section className="dmd-appearance-panel" role="dialog" aria-label="Documentation appearance">
          <div className="dmd-appearance-heading">
            <span>Appearance</span>
            <button
              type="button"
              className="dmd-appearance-close"
              aria-label="Close appearance menu"
              onClick={() => setIsOpen(false)}
            >
              ×
            </button>
          </div>

          <div className="dmd-appearance-section">
            <div className="dmd-appearance-label">Theme family</div>
            <div className="dmd-theme-family-grid">
              {families.map((item) => (
                <button
                  type="button"
                  key={item.family}
                  className={`dmd-theme-family-card ${family === item.family ? "active" : ""}`}
                  aria-pressed={family === item.family}
                  onClick={() => setFamily(item.family)}
                >
                  <span className={`dmd-theme-preview dmd-theme-preview-${item.family}`} aria-hidden="true">
                    <span />
                    <span />
                    <span />
                  </span>
                  <span className="dmd-theme-family-name">{item.label}</span>
                  <span className="dmd-theme-family-description">{item.description}</span>
                </button>
              ))}
            </div>
          </div>

          <fieldset className="dmd-appearance-section">
            <legend className="dmd-appearance-label">Mode</legend>
            <div className="dmd-segmented-control">
              {(["auto", "light", "dark"] as const).map((item) => (
                <button
                  type="button"
                  key={item}
                  className={mode === item ? "active" : ""}
                  onClick={() => setMode(item)}
                >
                  {item}
                </button>
              ))}
            </div>
            <button type="button" className="dmd-appearance-quick-mode" onClick={toggleMode}>
              Use {resolvedMode === "dark" ? "light" : "dark"} now
            </button>
          </fieldset>

          <fieldset className="dmd-appearance-section">
            <legend className="dmd-appearance-label">Reading density</legend>
            <div className="dmd-segmented-control">
              {(["comfortable", "compact"] as ThemeDensity[]).map((item) => (
                <button
                  type="button"
                  key={item}
                  className={density === item ? "active" : ""}
                  onClick={() => setDensity(item)}
                >
                  {item}
                </button>
              ))}
            </div>
          </fieldset>
        </section>
      )}
    </div>
  );
};
